env:
  node: true
  commonjs: true
  es2021: true
extends: [standard-with-typescript,prettier]
overrides: []
parserOptions:
  ecmaVersion: latest
  project: [./tsconfig.json]
rules: {
  "@typescript-eslint/strict-boolean-expressions": "warn",
  "@typescript-eslint/no-unused-vars": "warn",
  "@typescript-eslint/no-namespace": "off",

}
